
states = {
    "PR": 'P1',
    "AC": 'A1',
    "AL": 'A2',
    "AP": 'A3',
    "AM": 'A4',
    "BA": 'B1',
    "CE": 'C1',
    "DF": 'D1',
    "ES": 'E1',
    "GO": 'G1',
    "MA": 'M1',
    "MT": 'M2',
    "MS": 'M3',
    "MG": 'M4',
    "PA": 'P2',
    "PB": 'P3',
    "PE": 'P4',
    "PI": 'P5',
    "RJ": 'R1',
    "RN": 'R2',
    "RS": 'R3',
    "RO": 'R4',
    "RR": 'R5',
    "SC": 'S1',
    "SP": 'S2',
    "SE": 'S3',
    "TO": 'T1',
    "XX": "XX"
}